// <auto-generated />
using System;
using KartInventoryService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KartInventoryService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260725142337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KartInventoryService.Domain.Inventory.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<string>("ReleaseReason")
                        .HasColumnType("text")
                        .HasColumnName("release_reason");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("ReservationId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_reservations_expiry_sweep")
                        .HasFilter("status = 'reserved'");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_reservations_order_id")
                        .HasFilter("status = 'reserved'");

                    b.ToTable("reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_reservations_qty_positive", "qty > 0");

                            t.HasCheckConstraint("CK_reservations_release_reason", "release_reason IS NULL OR release_reason IN ('explicit_call', 'order_cancelled', 'compensation_triggered', 'ttl_expiry')");

                            t.HasCheckConstraint("CK_reservations_status", "status IN ('reserved', 'released', 'expired')");
                        });
                });

            modelBuilder.Entity("KartInventoryService.Domain.Inventory.WarehouseAllocation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<string>("WarehouseId")
                        .HasColumnType("text")
                        .HasColumnName("warehouse_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("ReservationId", "WarehouseId");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("idx_reservation_allocations_reservation");

                    b.ToTable("reservation_allocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_reservation_allocations_qty_positive", "qty > 0");
                        });
                });

            modelBuilder.Entity("KartInventoryService.Domain.Inventory.WarehouseStock", b =>
                {
                    b.Property<string>("WarehouseId")
                        .HasColumnType("text")
                        .HasColumnName("warehouse_id");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("AvailableQty")
                        .HasColumnType("integer")
                        .HasColumnName("available_qty");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("ReplenishmentThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("replenishment_threshold");

                    b.Property<int>("TargetStockingLevel")
                        .HasColumnType("integer")
                        .HasColumnName("target_stocking_level");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("WarehouseId", "Sku");

                    b.HasIndex("Sku", "WarehouseId")
                        .HasDatabaseName("idx_warehouse_stock_sku");

                    b.ToTable("warehouse_stock", null, t =>
                        {
                            t.HasCheckConstraint("CK_warehouse_stock_available_qty_non_negative", "available_qty >= 0");
                        });

                    b.HasData(
                        new
                        {
                            WarehouseId = "WH-1",
                            Sku = "DEMO-SKU-1",
                            AvailableQty = 100,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:initial-load",
                            ReplenishmentThreshold = 20,
                            TargetStockingLevel = 100,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system:initial-load"
                        },
                        new
                        {
                            WarehouseId = "WH-2",
                            Sku = "DEMO-SKU-1",
                            AvailableQty = 30,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system:initial-load",
                            ReplenishmentThreshold = 10,
                            TargetStockingLevel = 50,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "system:initial-load"
                        });
                });

            modelBuilder.Entity("KartInventoryService.Infrastructure.Messaging.InventoryOutboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("AggregateRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_ref");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("EventId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_inventory_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("inventory_outbox_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventory_outbox_events_event_type", "event_type IN ('InventoryReserved', 'InventoryReservationFailed', 'InventoryReleased', 'InventoryReplenished')");
                        });
                });

            modelBuilder.Entity("KartInventoryService.Domain.Inventory.WarehouseAllocation", b =>
                {
                    b.HasOne("KartInventoryService.Domain.Inventory.Reservation", null)
                        .WithMany("Allocations")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KartInventoryService.Domain.Inventory.Reservation", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
